### ISSUE TITLE
Extra Git and SQL content showing up at the bottum

### ISSUE THREAD

**Issue by lmichael107** [UW-Madison-ACI/2017-08-30-uwmadison-swc#1]
I couldn't figure out how to fix it, but there are some extra bits of info showing up at the bottom of the rendered index.html page, that currently appear to be part of "Setup", though they're not. Titled "Version Control with Git" and "Managing Data with SQL".

**Comment by lmichael107** [comment]
Pretty sure it's the syllabus (_includes/sc/syllabus.html), but only part of it shows up in the rendered page?

**Comment by ChristinaLK** [comment]
I think I fixed it.  Darn includes + commenting.  :(
